spring:
  datasource.url: jdbc:h2:file:./camunda-h2-database
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616



camunda.bpm.admin-user:
  id: demo
  password: demo

logging:
  file:
    path: /log
    max-size: 500MB
    max-history: 10
#  level:
#    root: debug

workflow:
  extrc:
    # rest api 서버 URL
    serverIp: http://localhost:8070

#server.port: 8070

