spring:
  datasource.url: jdbc:h2:file:./camunda-h2-database
  activemq:
    user: admin
    password: admin
    broker-url: tcp://172.50.17.241:61616

logging:
  file:
    name: ~/logs/test.logss
    max-history: 30
    max-size: 10MB
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  level:
    org:
      springframework: INFO


workflow:
  extrc:
    # rest api 서버 URL
    serverIp: http://localhost:8070



