spring:
  datasource.url: jdbc:h2:file:./camunda-h2-database
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616



camunda.bpm.admin-user:
  id: demo
  password: demo

